name: CI

on:
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/local.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/local.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Type checking with Mypy
        run: |
          mypy .

      - name: Test with pytest
        run: |
          PYTHONPATH=. alembic upgrade head && pytest app/tests
